spring:
  application:
    name: SetStatus-Service
server:
  port: 1504
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true