spring:
  application:
    name: GetDocumentById-Service
server:
  port: 1500
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true